In [1]:
import torch
import torch.nn.functional as F

In [4]:
z = torch.FloatTensor([3,4,3])
y_hat = F.softmax(z, dim=0)
print(y_hat)

tensor([0.2119, 0.5761, 0.2119])


In [7]:
z = torch.rand(3,5,requires_grad=True)
print(z)
print(z.sum(dim=1))
y_hat = F.softmax(z, dim=1)
print(y_hat)
print(y_hat.sum(dim=1))

tensor([[0.9884, 0.1221, 0.4612, 0.1514, 0.1027],
        [0.4120, 0.4914, 0.1037, 0.2252, 0.3585],
        [0.1528, 0.3426, 0.1447, 0.0615, 0.8389]], requires_grad=True)
tensor([1.8258, 1.5908, 1.5406], grad_fn=<SumBackward1>)
tensor([[0.3501, 0.1472, 0.2067, 0.1516, 0.1444],
        [0.2176, 0.2356, 0.1599, 0.1806, 0.2063],
        [0.1639, 0.1982, 0.1626, 0.1496, 0.3256]], grad_fn=<SoftmaxBackward0>)
tensor([1., 1., 1.], grad_fn=<SumBackward1>)


In [17]:
# 5미만인 랜덤한 정수를 첫번째 차원이 3개인 행렬(리스트)로 만들어줌
y= torch.randint(5, (3,)).long()
print(y)
y_one_hot = torch.zeros_like(y_hat)
print(y_one_hot)
# unsqueeze : 차원을 하나 높여줌
print(y.unsqueeze(1))

# 파라미터 설명(dim, index, value)
y_one_hot.scatter_(1,y.unsqueeze(1), 1)
print(y_one_hot)

tensor([2, 4, 2])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[2],
        [4],
        [2]])
tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.]])


In [18]:
import torch.nn as nn
import torch.optim as optim

In [35]:
torch.manual_seed(1)
x_data=[[1,2,1,1,],
        [2,1,3,2], 
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]

In [39]:
x_train = torch.FloatTensor(x_data)
y_train = torch.LongTensor(y_data)
print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8])


In [40]:
y_one_hot = torch.zeros(8,3)
print(y_one_hot)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [41]:
w = torch.zeros((4,3), requires_grad=True)
b = torch.zeros((1,3), requires_grad=True)
print(w)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [42]:
optimizer = optim.SGD([w,b], lr=0.1)
epochs = 10001

In [43]:
for epoch in range(epochs):
    y_hat = F.softmax(x_train.matmul(w)+b, dim=1)
    cost = (y_one_hot*-torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0 :
        print(f'epoch : {epoch}, cost : {cost.item()}')


epoch : 0, cost : 1.0986123085021973
epoch : 100, cost : 0.7041995525360107
epoch : 200, cost : 0.6229996085166931
epoch : 300, cost : 0.5657169222831726
epoch : 400, cost : 0.5152913331985474
epoch : 500, cost : 0.46766167879104614
epoch : 600, cost : 0.4212779700756073
epoch : 700, cost : 0.3754016160964966
epoch : 800, cost : 0.3297654986381531
epoch : 900, cost : 0.2850721478462219
epoch : 1000, cost : 0.2481546849012375
epoch : 1100, cost : 0.23267611861228943
epoch : 1200, cost : 0.22139869630336761
epoch : 1300, cost : 0.21112915873527527
epoch : 1400, cost : 0.20173649489879608
epoch : 1500, cost : 0.1931133270263672
epoch : 1600, cost : 0.18516966700553894
epoch : 1700, cost : 0.1778293251991272
epoch : 1800, cost : 0.17102724313735962
epoch : 1900, cost : 0.16470739245414734
epoch : 2000, cost : 0.15882128477096558
epoch : 2100, cost : 0.15332657098770142
epoch : 2200, cost : 0.14818626642227173
epoch : 2300, cost : 0.14336799085140228
epoch : 2400, cost : 0.1388428956270218


In [45]:
y_hat = F.softmax(x_train.matmul(w) + b, dim=1)
print(y_hat)
print(y_one_hot)

tensor([[7.9508e-11, 6.5690e-06, 9.9999e-01],
        [1.7811e-04, 1.9474e-02, 9.8035e-01],
        [1.1670e-13, 4.1809e-02, 9.5819e-01],
        [6.1379e-10, 9.6248e-01, 3.7520e-02],
        [7.2622e-02, 9.2453e-01, 2.8516e-03],
        [3.8537e-02, 9.6146e-01, 7.0804e-08],
        [9.1230e-01, 8.7705e-02, 8.1008e-08],
        [9.9212e-01, 7.8797e-03, 5.7659e-11]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [46]:
for y in y_hat:
    print(y.argmax().item())

2
2
2
1
1
1
0
0


In [47]:
model = nn.Linear(4,3)  #input_dim = 4, output_dim=3
optimizer = optim.SGD(model.parameters(), lr=0.1)
epochs=10001

In [48]:
for epoch in range(epochs):
    y_hat = model(x_train)
    cost = F.cross_entropy(y_hat, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(f'epoch : {epoch}, cost : {cost.item()}')

epoch : 0, cost : 1.6167852878570557
epoch : 100, cost : 0.6588909029960632
epoch : 200, cost : 0.5734434127807617
epoch : 300, cost : 0.5181514024734497
epoch : 400, cost : 0.4732654392719269
epoch : 500, cost : 0.4335160553455353
epoch : 600, cost : 0.39656299352645874
epoch : 700, cost : 0.3609141707420349
epoch : 800, cost : 0.3253922760486603
epoch : 900, cost : 0.2891782224178314
epoch : 1000, cost : 0.254148006439209
epoch : 1100, cost : 0.23497344553470612
epoch : 1200, cost : 0.2234926074743271
epoch : 1300, cost : 0.21305321156978607
epoch : 1400, cost : 0.20350952446460724
epoch : 1500, cost : 0.1947513222694397
epoch : 1600, cost : 0.1866869032382965
epoch : 1700, cost : 0.17923785746097565
epoch : 1800, cost : 0.17233797907829285
epoch : 1900, cost : 0.1659296602010727
epoch : 2000, cost : 0.15996332466602325
epoch : 2100, cost : 0.1543959230184555
epoch : 2200, cost : 0.149189293384552
epoch : 2300, cost : 0.14431047439575195
epoch : 2400, cost : 0.1397300809621811
epoch 

In [52]:
preds=model(x_train)
print(preds)

for pred in preds:
    print(pred.argmax().item())

tensor([[-11.4190,  -0.1089,  11.8240],
        [ -4.3004,   0.4547,   4.3716],
        [-18.3870,   8.3334,  11.4634],
        [-12.6073,   8.7538,   5.5110],
        [  0.9640,   3.5059,  -2.2739],
        [  4.2154,   7.4301,  -9.0255],
        [  7.0720,   4.7319,  -9.1734],
        [ 10.5025,   5.6714, -13.0728]], grad_fn=<AddmmBackward0>)
2
2
2
1
1
1
0
0


In [58]:
class SoftmaxModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [59]:
model = SoftmaxModel()
optimizer = optim.SGD(model.parameters(), lr=0.1)
epochs = 10001

In [60]:
for epoch in range(epochs):
    y_hat = model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(f'eopch : {epoch}, cost: {cost.item()}')


eopch : 0, cost: 2.6837055683135986
eopch : 100, cost: 0.6966274976730347
eopch : 200, cost: 0.6156858205795288
eopch : 300, cost: 0.5584627985954285
eopch : 400, cost: 0.5081623792648315
eopch : 500, cost: 0.46063682436943054
eopch : 600, cost: 0.41430869698524475
eopch : 700, cost: 0.36844050884246826
eopch : 800, cost: 0.3228070139884949
eopch : 900, cost: 0.27836117148399353
eopch : 1000, cost: 0.24378979206085205
eopch : 1100, cost: 0.22987177968025208
eopch : 1200, cost: 0.21881912648677826
eopch : 1300, cost: 0.20874805748462677
eopch : 1400, cost: 0.1995321661233902
eopch : 1500, cost: 0.19106729328632355
eopch : 1600, cost: 0.18326592445373535
eopch : 1700, cost: 0.1760539710521698
eopch : 1800, cost: 0.16936816275119781
eopch : 1900, cost: 0.16315393149852753
eopch : 2000, cost: 0.1573638617992401
eopch : 2100, cost: 0.1519566774368286
eopch : 2200, cost: 0.14689670503139496
eopch : 2300, cost: 0.14215199649333954
eopch : 2400, cost: 0.13769464194774628
eopch : 2500, cost: 0.

In [61]:
predictions = model(x_train)
print(predictions)
for pred in predictions:
    print(pred.argmax().item())

tensor([[-1.0856e+01,  4.5740e-01,  1.2281e+01],
        [-4.6509e+00, -1.7458e-02,  3.9047e+00],
        [-1.8929e+01,  7.6294e+00,  1.0764e+01],
        [-1.3611e+01,  7.4681e+00,  4.2205e+00],
        [ 2.1079e+00,  4.6548e+00, -1.1292e+00],
        [ 2.9079e+00,  6.1276e+00, -9.5868e+00],
        [ 7.3436e+00,  4.9986e+00, -8.6052e+00],
        [ 1.0806e+01,  5.9695e+00, -1.2416e+01]], grad_fn=<AddmmBackward0>)
2
2
2
1
1
1
0
0


In [64]:
import sklearn.datasets as datasets
iris = datasets.load_iris()
iris.data
iris.target
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [80]:
x_train = torch.FloatTensor(iris.data)
y_train = torch.LongTensor(iris.target)
print(x_train.size())
print(y_train.size())

torch.Size([150, 4])
torch.Size([150])


In [ ]:
class SoftmaxModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)
        # self.softmax = nn.Softmax()

    def forward(self, x):

        # cross_entropy()를 사용하면 맨 마지막 단의 softmax()는 생략 가능 
        return self.linear(x)      
        # return self.softmax(self.linear(x))

In [89]:
model = SoftmaxModel()
optimizer = optim.SGD(model.parameters(), lr=0.1)
epochs=10001

In [90]:
for epoch in range(epochs):
    y_hat = model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(f'eopch : {epoch}, cost: {cost.item()}')


eopch : 0, cost: 1.5569689273834229
eopch : 100, cost: 0.4369971752166748
eopch : 200, cost: 0.25845861434936523
eopch : 300, cost: 0.21572257578372955
eopch : 400, cost: 0.1886710673570633
eopch : 500, cost: 0.1699049323797226
eopch : 600, cost: 0.15607570111751556
eopch : 700, cost: 0.1454285979270935
eopch : 800, cost: 0.13695544004440308
eopch : 900, cost: 0.1300354301929474
eopch : 1000, cost: 0.12426526099443436
eopch : 1100, cost: 0.11937137693166733
eopch : 1200, cost: 0.11516137421131134
eopch : 1300, cost: 0.11149604618549347
eopch : 1400, cost: 0.1082719936966896
eopch : 1500, cost: 0.10541076958179474
eopch : 1600, cost: 0.10285170376300812
eopch : 1700, cost: 0.1005471795797348
eopch : 1800, cost: 0.09845922142267227
eopch : 1900, cost: 0.0965571478009224
eopch : 2000, cost: 0.09481591731309891
eopch : 2100, cost: 0.09321492165327072
eopch : 2200, cost: 0.09173690527677536
eopch : 2300, cost: 0.09036743640899658
eopch : 2400, cost: 0.08909427374601364
eopch : 2500, cost: 0

In [91]:
pred=model(x_train)
print(pred)

tensor([[ 1.4543e+01,  6.8317e+00, -2.2963e+01],
        [ 1.2351e+01,  6.6374e+00, -2.0392e+01],
        [ 1.3276e+01,  6.4941e+00, -2.1195e+01],
        [ 1.1657e+01,  6.2848e+00, -1.9512e+01],
        [ 1.4737e+01,  6.7322e+00, -2.3112e+01],
        [ 1.4498e+01,  6.4348e+00, -2.2809e+01],
        [ 1.3086e+01,  6.0765e+00, -2.0717e+01],
        [ 1.3462e+01,  6.6779e+00, -2.1786e+01],
        [ 1.1108e+01,  6.1441e+00, -1.8676e+01],
        [ 1.2396e+01,  6.8430e+00, -2.0826e+01],
        [ 1.5267e+01,  7.0711e+00, -2.4061e+01],
        [ 1.2574e+01,  6.4248e+00, -2.0758e+01],
        [ 1.2391e+01,  6.8005e+00, -2.0660e+01],
        [ 1.3131e+01,  6.4734e+00, -2.0872e+01],
        [ 1.8686e+01,  7.6311e+00, -2.7852e+01],
        [ 1.7941e+01,  6.8391e+00, -2.6653e+01],
        [ 1.6650e+01,  6.6571e+00, -2.4832e+01],
        [ 1.4328e+01,  6.5697e+00, -2.2433e+01],
        [ 1.4869e+01,  6.9937e+00, -2.3712e+01],
        [ 1.4896e+01,  6.5122e+00, -2.3157e+01],
        [ 1.3085e+01

In [92]:
accuracys = []
for i in range(len(pred)):
    accuracys.append(y_train[i]==pred[i].argmax())

print(torch.FloatTensor(accuracys).sum()/len(accuracys))


tensor(0.9800)
