In [48]:
# ! pip install tensorflow

In [49]:
import numpy as np
import tensorflow as tf


In [50]:
x_train = np.array([[1,2], [2,3], [3,4], [4,5], [5,6]], dtype=np.float32)
y_train = np.array([[3], [5], [7], [9], [11]],  dtype=np.float32)

In [51]:
class LinearRegressionModel(tf.Module):
    def __init__(self):
        self.w = tf.Variable(tf.random.normal([2, 1]), name='weight', dtype=tf.float32)
        self.b = tf.Variable(tf.random.normal([1]), name='bias', dtype=tf.float32)

    def __call__(self, x):
        return tf.matmul(x, self.w) + self.b

In [52]:
a = tf.Variable(10.0, name='a')
b = tf.Variable(20.0, name='b')
print(a)
print(b)
print(a + b)

<tf.Variable 'a:0' shape=() dtype=float32, numpy=10.0>
<tf.Variable 'b:0' shape=() dtype=float32, numpy=20.0>
tf.Tensor(30.0, shape=(), dtype=float32)


In [53]:
def loos_fn(model, x, y):
    y_pred = model(x)
    return tf.reduce_mean(tf.square(y - y_pred)) # Mean Squared Error

In [54]:
model = LinearRegressionModel()
optimizer = tf.optimizers.SGD(learning_rate=0.01)

for epoch in range(2000):
    # 자동 미분을 수행하기 위해 제공되는 자동 그라디언트 recoding 기능을 사용합니다.
    # tf.GradientTape()는 자동 미분을 위한 컨텍스트 매니저입니다.
    # 이 컨텍스트 매니저 안에서 연산을 수행하면, 그라디언트를 계산할 수 있습니다.
    # tape는 연산을 기록하고, 나중에 그라디언트를 계산할 수 있게 합니다.
    with tf.GradientTape() as tape:    
        loss = loos_fn(model, x_train, y_train)

        gradients = tape.gradient(loss, [model.w, model.b])
        optimizer.apply_gradients(zip(gradients, [model.w, model.b]))

    if epoch % 100 == 0:
        print(f'Epoch {epoch}, Loss: {loss.numpy()}, Weights: {model.w.numpy().flatten()}, Bias: {model.b.numpy().flatten()}')
        

Epoch 0, Loss: 202.07211303710938, Weights: [0.5285529  0.07555723], Bias: [-0.2819097]
Epoch 100, Loss: 0.0035919328220188618, Weights: [1.1298343  0.90957224], Bias: [-0.04917621]
Epoch 200, Loss: 0.0016026556259021163, Weights: [1.1056604  0.92066175], Bias: [-0.01391278]
Epoch 300, Loss: 0.0007150806486606598, Weights: [1.0895128 0.9280695], Bias: [0.00964206]
Epoch 400, Loss: 0.00031904541538096964, Weights: [1.0787271 0.9330174], Bias: [0.02537589]
Epoch 500, Loss: 0.00014235595881473273, Weights: [1.0715226  0.93632233], Bias: [0.03588559]
Epoch 600, Loss: 6.351657066261396e-05, Weights: [1.06671    0.93853015], Bias: [0.04290578]
Epoch 700, Loss: 2.8338443371467292e-05, Weights: [1.063495  0.9400051], Bias: [0.04759497]
Epoch 800, Loss: 1.2644212802115362e-05, Weights: [1.0613477  0.94099027], Bias: [0.05072713]
Epoch 900, Loss: 5.6411527111777104e-06, Weights: [1.0599134 0.9416483], Bias: [0.05281926]
Epoch 1000, Loss: 2.516193490009755e-06, Weights: [1.0589554 0.9420878], Bia

In [56]:
pred = model(np.array([[6,7], [7,8], [8,9]], dtype=np.float32))
print(pred.numpy().flatten())

[13.000047 15.000066 17.000082]


In [57]:
import pandas as pd
df = pd.read_csv('data/data-01-test-score.csv', header=None)
df

0   1    2    3
0   73  80   75  152
1   93  88   93  185
2   89  91   90  180
3   96  98  100  196
4   73  66   70  142
5   53  46   55  101
6   69  74   77  149
7   47  56   60  115
8   87  79   90  175
9   79  70   88  164
10  69  70   73  141
11  70  65   74  141
12  93  95   91  184
13  79  80   73  152
14  70  73   78  148
15  93  89   96  192
16  78  75   68  147
17  81  90   93  183
18  88  92   86  177
19  78  83   77  159
20  82  86   90  177
21  86  82   89  175
22  78  83   85  175
23  76  83   71  149
24  96  93   95  192

In [85]:
x_train = np.array(df.values[:,:-1], dtype=np.float32)
print(x_train)
y_train = np.array(df.values[:,-1].reshape(-1, 1), dtype=np.float32)
print(y_train)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [86]:
class LinearRegressionModel(tf.Module):
    def __init__(self):
        self.w = tf.Variable(tf.random.normal([3, 1]), name='weight', dtype=tf.float32)
        self.b = tf.Variable(tf.random.normal([1]), name='bias', dtype=tf.float32)

    def __call__(self, x):
        return tf.matmul(x, self.w) + self.b

In [87]:
def loos_fn(model, x, y):
    y_pred = model(x)
    return tf.reduce_mean(tf.square(y - y_pred)) # Mean Squared Error

In [88]:
model = LinearRegressionModel()
optimizer = tf.optimizers.SGD(learning_rate=0.00001)

for epoch in range(20000):
    with tf.GradientTape() as tape:    
        loss = loos_fn(model, x_train, y_train)

        gradients = tape.gradient(loss, [model.w, model.b])
        optimizer.apply_gradients(zip(gradients, [model.w, model.b]))

    if epoch % 100 == 0:
        print(f'Epoch {epoch}, Loss: {loss.numpy()}, Weights: {model.w.numpy().flatten()}, Bias: {model.b.numpy().flatten()}')
        

Epoch 0, Loss: 3896.11376953125, Weights: [ 0.550462    1.4222746  -0.37521136], Bias: [-1.2999083]
Epoch 100, Loss: 66.99120330810547, Weights: [ 0.693824    1.5283172  -0.16084917], Bias: [-1.2977343]
Epoch 200, Loss: 61.843780517578125, Weights: [ 0.6842014   1.4823879  -0.10661794], Bias: [-1.2974764]
Epoch 300, Loss: 57.131893157958984, Weights: [ 0.6748723   1.4385221  -0.05468828], Bias: [-1.2972332]
Epoch 400, Loss: 52.81867218017578, Weights: [ 0.66582674  1.3966289  -0.00496163], Bias: [-1.2970045]
Epoch 500, Loss: 48.87028884887695, Weights: [0.6570556  1.3566204  0.04265668], Bias: [-1.2967917]
Epoch 600, Loss: 45.2557373046875, Weights: [0.64855    1.3184133  0.08825701], Bias: [-1.2965922]
Epoch 700, Loss: 41.94679641723633, Weights: [0.640301  1.2819276 0.1319256], Bias: [-1.2964058]
Epoch 800, Loss: 38.91754150390625, Weights: [0.6323001  1.2470876  0.17374521], Bias: [-1.2962317]
Epoch 900, Loss: 36.14426803588867, Weights: [0.6245393  1.21382    0.21379499], Bias: [-1

In [94]:
prediected = model(np.array([[73.0, 80.0, 75.0], [98.0, 77.0, 80.0], [86.0, 90.0, 80.0]], dtype=np.float32))
print("Predicted values for 6.0, 7.0, 8.0:", prediected.numpy().flatten())

Predicted values for 6.0, 7.0, 8.0: [152.83798 165.87602 168.51343]
