In [1]:
! pip install torch

   ---------------------------------------- 0.0/216.1 MB ? eta -:--:--
   - -------------------------------------- 7.3/216.1 MB 75.3 MB/s eta 0:00:03
   ---- ----------------------------------- 26.7/216.1 MB 65.1 MB/s eta 0:00:03
   ----- ---------------------------------- 30.4/216.1 MB 66.4 MB/s eta 0:00:03
   ------ --------------------------------- 34.3/216.1 MB 41.9 MB/s eta 0:00:05
   -------- ------------------------------- 48.0/216.1 MB 47.0 MB/s eta 0:00:04
   ---------- ----------------------------- 57.1/216.1 MB 46.1 MB/s eta 0:00:04
   ------------ --------------------------- 65.3/216.1 MB 44.7 MB/s eta 0:00:04
   ------------ --------------------------- 69.2/216.1 MB 44.1 MB/s eta 0:00:04
   -------------- ------------------------- 81.0/216.1 MB 43.4 MB/s eta 0:00:04
   ---------------- ----------------------- 91.0/216.1 MB 43.6 MB/s eta 0:00:03
   ------------------ --------------------- 98.6/216.1 MB 43.7 MB/s eta 0:00:03
   ------------------- ------------------- 108.0/2

In [2]:
import torch

In [5]:
t1 = torch.tensor([1, 2, 3], dtype=torch.float32)  # dtype 은 실수로 지정
t2 = torch.tensor([[4, 5], [6, 7]])
t3 = torch.tensor([1.2, 2.3, 3.4])
print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([[4, 5],
        [6, 7]])
tensor([1.2000, 2.3000, 3.4000])


In [ ]:
tf = torch.FloatTensor([1, 2, 3])  # FloatTensor로 실수 텐서 생성
f1 = torch.LongTensor([1, 2, 3])  # LongTensor로 정수 텐서 생성 ( int64 )
tb = torch.ByteTensor([1, 2, 3])  # ByteTensor로 바이트 텐서 생성
print(tf)
print(f1)
print(tb)
# 텐서의 데이터 타입 확인

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.uint8)


In [7]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
# NumPy 배열을 PyTorch 텐서로 변환
x= torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)
print(type(x))  # 텐서의 타입 확인

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
<class 'torch.Tensor'>


In [ ]:
# PyTorch 텐서를 NumPy 배열로 변환
b = x.numpy()
print(b)
print(type(b))  # NumPy 배열의 타입 확인

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [10]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print(type(x), x.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'> torch.int64


In [14]:
# PyTorch 텐서의 데이터 타입 변경(long -> float)
y=x.float()
print(y)
print(y.dtype)  # dtype이 float32로 변경됨

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


In [12]:
# PyTorch 텐서의 데이터 타입 변경(float -> long)
z=x.long()
print(z)
print(z.dtype)  # dtype이 int64로 변경됨

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


In [15]:
# PyTorch 텐서의 데이터 타입 변경(float -> byte)
z1 = y.byte()
print(z1)
print(z1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)
torch.uint8


In [20]:
a = np.arange(1,13).reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
x= torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
print(x.shape)  # 텐서의 형태 확인
print(x.size())  # 텐서의 크기 확인
print(x.dim())  # 텐서의 차원 수 확인
print(x.ndim)  # 텐서의 차원 수 확인 (dim과 동일)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
3


In [25]:
print(x.size(0))  # 첫 번째 차원의 크기
print(x.size(1))  # 두 번째 차원의 크기
print(x.size(2))  # 세 번째 차원의 크기
print(x.size(-1))  # 마지막 차원의 크기 (세 번째 차원)

3
2
2
2


In [27]:
# 기본 연산
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
# 덧셈
print(x + y) # 결과: tensor([[ 6,  8], [10, 12]])
# 뺄셈
print(x - y) # 결과: tensor([[-4, -4], [-4, -4]])
# 곱셈 (원소별 곱셈)
print(x * y) # 결과: tensor([[ 5, 12], [21, 32]])
# 나눗셈 (원소별 나눗셈)
print(x / y) # 결과: tensor([[0.2000, 0.3333], [0.4286, 0.5000]])
# 행렬 곱셈
print(torch.matmul(x, y)) # 결과: tensor([[19, 22], [43, 50]])
# 행렬 곱셈 (연산자 사용)
print(x @ y) # 결과: tensor([[19, 22], [43, 50]])
# 스칼라 곱셈
print(x * 2) # 결과: tensor([[2, 4], [6, 8]])
# 스칼라 나눗셈
print(x / 2) # 결과: tensor([[0.5000, 1.0000], [1.5000, 2.0000]])
# 스칼라 덧셈
print(x + 2) # 결과: tensor([[3, 4], [5, 6]])
# 스칼라 뺄셈
print(x - 2) # 결과: tensor([[-1,  0], [ 1,  2]])
# 나머지 구하기
print(x % y) # 결과: tensor([[1, 2], [3, 4]])
# 정수몫 나눗셈
print(x // y)   # 결과: tensor([[0, 0], [0, 0]])


tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[2, 4],
        [6, 8]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[3, 4],
        [5, 6]])
tensor([[-1,  0],
        [ 1,  2]])
tensor([[1, 2],
        [3, 4]])
tensor([[0, 0],
        [0, 0]])


In [36]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(a == b)  # 두 텐서가 같은지 비교
print(a != b)  # 두 텐서가 다른지 비교
print(a < b)   # a의 원소가 b의 원소보다 작은지 비교
print(a <= b)  # a의 원소가 b의 원소보다 작거나 같은지 비교
print(a > b)   # a의 원소가 b의 원소보다 큰지 비교
print(a >= b)  # a의 원소가 b의 원소보다 크거나 같은지 비교
print(a.eq(b))  # a와 b가 같은지 비교 (eq는 equal의 약자)
print(a.ne(b))  # a와 b가 다른지 비교 (ne는 not equal의 약자)
print(a.lt(b))   # a의 원소가 b의 원소보다 작은지 비교 (lt는 less than의 약자
print(a.le(b))   # a의 원소가 b의 원소보다 작거나 같은지 비교 (le는 less than or equal의 약자
print(a.gt(b))   # a의 원소가 b의 원소보다 큰지 비교 (gt는 greater than의 약자
print(a.ge(b))   # a의 원소가 b의 원소보다 크거나 같은지 비교 (ge는 greater than or equal의 약자
# 논리 연산
print(a.logical_and(b))  # a와 b의 원소가 모두 True인 경우 True
print(a.logical_or(b))   # a와 b의 원소 중 하나라도 True인 경우 True
# 논리 연산 (and, or, not)
print(torch.logical_and(a, b))  # a와 b의 원소가 모두 True인 경우 True
print(torch.logical_or(a, b))   # a와 b의 원소 중 하나라도 True인 경우 True
# 논리 부정
print(torch.logical_not(a))  # a의 원소가 False인 경우 True
# 논리 연산 (and, or, not)
print(torch.all(a))  # a의 모든 원소가 True인 경우 True
print(torch.any(a))  # a의 원소 중 하나라도 True인 경우 True


tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor([[False, False],
        [False, False]])
tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
tensor([[False, False],
        [False, False]])
tensor(True)
tensor(True)


In [37]:
print(a.mul(b))  # 행렬 곱셈
print(a)

tensor([[ 5, 12],
        [21, 32]])
tensor([[1, 2],
        [3, 4]])


In [38]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)


In [39]:
print(x.sum())  # 모든 원소의 합
print(x.sum(dim=0))  # 각 열의 합
print(x.sum(dim=1))  # 각 행의 합
print(x.sum(dim=-1))  # 마지막 차원의 합

tensor(78)
tensor([15, 18, 21, 24])
tensor([10, 26, 42])
tensor([10, 26, 42])


In [40]:
y = torch.tensor([1, 2, 3, 4])
print(y)

tensor([1, 2, 3, 4])


In [ ]:
print(x+y)  # 브로드캐스팅을 이용한 덧셈
# 계산이 가능하도록 차원을 맞춰줘야함.(차원이 안맞으면 계산이 불가능)

tensor([[ 2,  4,  6,  8],
        [ 6,  8, 10, 12],
        [10, 12, 14, 16]])


In [42]:
a = np.arange(1, 13).reshape(3, 2, 2)
print(a)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
y = torch.tensor([[1, 2], [3, 4]])  # 2차원 텐서
print(x)
print(y)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]])


In [ ]:
print(x)
# view()와 reshape()를 사용하여 텐서의 형태를 변경할 수 있습니다.(두개 의 차이는 reshape()는 메모리 복사를 하지 않지만, view()는 메모리 복사를 합니다.)
print(x.view(3, 4))  # 3x4 형태로 변환
print(x.view(2, 6))  # 2x6 형태로 변환
print(x.view(3, -1))  # -1을 사용하여 자동으로 차원 계산
print(x.view(-1, 4))  # -1을 사용하여 자동으로 차원 계산
print(x.reshape(4, 3))  # 4x3 형태로 변환

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [52]:
# Squeeze() : 텐서의 차원 중 크기가 1인 차원을 제거합니다.
# Unsqueeze() : 텐서에 새로운 차원을 추가합니다.

y = x.view(3, 1, 4)
print(y)
z1 = y.squeeze()  # 크기가 1인 차원을 제거하여 3x4 형태로 변환
print(z1)  # 크기가 1인 차원을 제거하여 3x4 형태로 변환
z2 = z1.unsqueeze(1) 
print(z2)  # 두 번째 차원에 새로운 차원을 추가하여 1x3x4 형태로 변환
z3 = z1.unsqueeze(-1)  
print(z3) # 마지막 차원에 새로운 차원을 추가하여 3x4x1 형태로 변환


tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)
tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]], dtype=torch.int32)


In [53]:
print(x[0])  # 첫 번째 행을 선택
print(x[0, 0]) # 첫 번째 행의 첫 번째 열을 선택
print(x[0, 0, 0])  # 첫 번째 행의 첫 번째 열의 첫 번째 깊이 값을 선택

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([1, 2], dtype=torch.int32)
tensor(1, dtype=torch.int32)


In [58]:
print(x[0,:])   # 첫 번째 행의 모든 열을 선택
print(x[0, : , -1])  # 첫 번째 행의 마지막 열을 선택
print(x[1,:,-1])  # 두 번째 행의 마지막 열을 선택

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([2, 4], dtype=torch.int32)
tensor([6, 8], dtype=torch.int32)


In [61]:
a = np.arange(1, 41).reshape(10,4)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]], dtype=torch.int32)


In [67]:
split_x = torch.split(x, 4, dim=0)  # 첫 번째 차원(행)을 기준으로 2개씩 나눔
# print(split_x)  # 나눠진 텐서들 출력
for  sx in split_x:
    print(sx)  # 각 나눠진 텐서의 크기 출력
    print(sx.shape)  # 각 나눠진 텐서의 형태 출력

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
torch.Size([4, 4])
tensor([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]], dtype=torch.int32)
torch.Size([4, 4])
tensor([[33, 34, 35, 36],
        [37, 38, 39, 40]], dtype=torch.int32)
torch.Size([2, 4])


In [79]:
chunks = x.chunk(5, dim=0)  # 첫 번째 차원(행)을 기준으로 4개로 나눔
for chunk in chunks:
    print(chunk)  # 각 나눠진 텐서의 크기 출력
    print(chunk.shape)  # 각 나눠진 텐서의 형태 출력

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[25, 26, 27, 28],
        [29, 30, 31, 32]], dtype=torch.int32)
torch.Size([2, 4])
tensor([[33, 34, 35, 36],
        [37, 38, 39, 40]], dtype=torch.int32)
torch.Size([2, 4])


In [80]:
a = np.arange(1,13).reshape(3,2,2)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)


In [81]:
indices = torch.LongTensor([2,1,0]) # 인덱스 텐서 생성
y = x.index_select(0, indices)  # 첫 번째 차원(행)을 기준으로 인덱스 선택
print(y)  # 선택된 행 출력

tensor([[[ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 1,  2],
         [ 3,  4]]], dtype=torch.int32)


In [82]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(11,23).reshape(3,4)
x = torch.from_numpy(a)  # NumPy 배열을 PyTorch 텐서로 변환
y = torch.from_numpy(b)  # NumPy 배열을 PyTorch 텐서로 변환
print(x)
print(y)


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]], dtype=torch.int32)


In [83]:
z = torch.cat((x, y), dim=0)  # 첫 번째 차원(행)을 기준으로 연결
print(z)  # 연결된 텐서 출력

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]], dtype=torch.int32)


In [84]:
z1 = torch.cat((x, y), dim=1)  # 두 번째 차원(열)을 기준으로 연결
print(z1)  # 연결된 텐서 출력

tensor([[ 1,  2,  3,  4, 11, 12, 13, 14],
        [ 5,  6,  7,  8, 15, 16, 17, 18],
        [ 9, 10, 11, 12, 19, 20, 21, 22]], dtype=torch.int32)


In [ ]:
z2 = torch.stack((x, y), dim=0)  # 첫 번째 차원(행)을 기준으로 스택
print(z2)  # 스택된 텐서 출력
# stack은 새로운 차원을 추가하여 텐서를 쌓는 반면, cat은 기존 차원을 기준으로 텐서를 연결합니다.

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]], dtype=torch.int32)


In [86]:
z3 = torch.stack((x, y), dim=1)  # 두 번째 차원(열)을 기준으로 스택
print(z3)  # 스택된 텐서 출력

tensor([[[ 1,  2,  3,  4],
         [11, 12, 13, 14]],

        [[ 5,  6,  7,  8],
         [15, 16, 17, 18]],

        [[ 9, 10, 11, 12],
         [19, 20, 21, 22]]], dtype=torch.int32)


In [89]:
X = torch.FloatTensor([[[1, 2]], [[3, 4]]])
print(X.size())  # 텐서의 크기 출력
print(X)

torch.Size([2, 1, 2])
tensor([[[1., 2.]],

        [[3., 4.]]])


In [ ]:
y = X.expand(2, 3, 2)  # 텐서를 확장하여 크기를 변경
print(y.size())  # 확장된 텐서의 크기 출력
print(y)  # 확장된 텐서 출력
# expand()는 메모리를 복사하지 않고, 원래 텐서의 데이터를 재사용하여 크기를 변경합니다.
# 따라서 메모리 사용량이 적고, 성능이 향상됩니다.

torch.Size([2, 3, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [92]:
x = torch.randperm(20)  # 0부터 19까지의 랜덤한 순열 생성
print(x)  # 랜덤한 순열 출력

tensor([11,  9, 18,  1, 14, 19, 13, 16,  4, 17,  0,  2,  8,  5,  3, 12, 10, 15,
         6,  7])


In [93]:
y = torch.randperm(3**3).reshape(3,3,3)  # 0부터 26까지의 랜덤한 순열을 3x3x3 형태로 변환
print(y)  # 랜덤한 순열 출력

tensor([[[ 8, 20,  6],
         [ 4, 12, 16],
         [14,  1, 15]],

        [[17, 23, 19],
         [21, 22,  0],
         [ 7, 25,  5]],

        [[18, 11,  3],
         [26, 13,  9],
         [10, 24,  2]]])


In [94]:
y1 = y.argmax(dim=0)  # 첫 번째 차원(행)을 기준으로 최대값의 인덱스 찾기
print(y1)  # 최대값의 인덱스 출력

tensor([[2, 1, 1],
        [2, 1, 0],
        [0, 1, 0]])


In [95]:
y2 = y.argmax(dim=1)  # 두 번째 차원(열)을 기준으로 최대값의 인덱스 찾기
print(y2)  # 최대값의 인덱스 출력

tensor([[2, 0, 1],
        [1, 2, 0],
        [1, 2, 1]])


In [97]:
y3 = y.argmax(dim=-1)  # 마지막 차원(깊이)을 기준으로 최대값의 인덱스 찾기
print(y3)  # 최대값의 인덱스 출력

tensor([[1, 2, 2],
        [1, 1, 1],
        [0, 0, 1]])


In [100]:
value, indices = torch.topk(y, k=2, dim = -1)  # 마지막 차원(깊이)을 기준으로 상위 k개의 값과 인덱스 찾기
print(value)  # 상위 k개의 값 출력
print(indices)  # 상위 k개의 인덱스 출력


tensor([[[20,  8],
         [16, 12],
         [15, 14]],

        [[23, 19],
         [22, 21],
         [25,  7]],

        [[18, 11],
         [26, 13],
         [24, 10]]])
tensor([[[1, 0],
         [2, 1],
         [2, 0]],

        [[1, 2],
         [1, 0],
         [1, 0]],

        [[0, 1],
         [0, 1],
         [1, 0]]])


In [102]:
x = torch.FloatTensor([i for i in range(1, 10)]).view(3, 3)  # 1부터 9까지의 값을 가지는 3x3 텐서 생성
print(x)  # 텐서 출력

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [103]:
mask = x > 5  # 5보다 큰 값을 가지는 마스크 생성
print(mask)  # 마스크 출력

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [104]:
y = x.masked_fill(mask, value=0)  # 마스크에 해당하는 값을 0으로 대체
print(y)  # 마스크가 적용된 텐서 출력

tensor([[1., 2., 3.],
        [4., 5., 0.],
        [0., 0., 0.]])


In [106]:
print(torch.ones(2,3))  # 2x3 형태의 텐서 생성
print(torch.zeros(2, 3))  # 2x3 형태의 텐서 생성 (모든 값이 0인 텐서)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [108]:
print(torch.ones_like(x))  # x와 같은 형태의 텐서 생성 (모든 값이 1인 텐서)
print(torch.zeros_like(x))  # x와 같은 형태의 텐서 생성 (모든 값이 0인 텐서)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
